all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | lower }}.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "mocks"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/dmksnnk/octo/internal/api:
    config:
      all: true
    interfaces:
      Service:
