// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package queries

import (
	"context"
)

const userByAPIKey = `-- name: UserByAPIKey :one
SELECT id, created_at, updated_at, deleted_at, email, api_key FROM users
WHERE api_key = $1::VARCHAR
AND deleted_at IS NULL
`

func (q *Queries) UserByAPIKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.ApiKey,
	)
	return i, err
}
