# Based on:
# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Image

on:
  create:
    tags:
      - "**"
  workflow_dispatch: # manual trigger

jobs:
  hugo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/dmksnnk/octo:${{ github.ref_name }}
            ghcr.io/dmksnnk/octo:latest
          platforms: linux/amd64
          labels: |
            org.opencontainers.image.source=https://${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          # use GitHub Actions cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
